(async function(){
  const U=DPRO_UI,app=document.getElementById('app');document.getElementById('nav').innerHTML=U.nav();U.setModeBanner('顧客本人の案件だけを表示');
  if(U.demo){
    const state=DproDemo.load(),uid='u-customer-home',cases=DproDemo.visibleCases(state,uid);renderDemoList(cases);return;
  }
  await U.protect(['customer'],async()=>{await loadLive()});
  function renderDemoList(cases){app.innerHTML=`<section class="hero"><span class="badge">DEMO CUSTOMER</span><h1>ご依頼・ご相談</h1></section><section class="grid grid-2" style="margin-top:18px">${cases.map(c=>`<div class="card"><h2>${U.esc(c.title)}</h2><p><span class="status ${c.urgency==='high'?'urgent':''}">${U.status(c.status)}</span></p><button class="btn open" data-id="${c.id}">案件を開く</button></div>`).join('')}</section><section id="detail" class="card" style="margin-top:18px"><h2>案件を選択してください</h2></section>`;document.querySelectorAll('.open').forEach(b=>b.onclick=()=>showDemo(b.dataset.id));if(cases[0])showDemo(cases[0].id)}
  function showDemo(id){const s=DproDemo.load(),c=s.cases.find(x=>x.id===id),ev=s.evidence.filter(e=>e.caseId===id),acts=s.nextActions.filter(a=>a.caseId===id&&a.status==='open');document.getElementById('detail').innerHTML=`<h2>${U.esc(c.title)}</h2><p><span class="status">${U.status(c.status)}</span> 次回: ${U.fmt(c.nextVisit)}</p><div class="split"><div><h3>相談内容を追加</h3><div class="field"><input id="caption" placeholder="例：シンク下で再度目撃"></div><button class="btn" id="add">相談メモを追加</button><div class="notice" style="margin-top:12px">危険を感じる場合や、刺傷・咬傷・動物との接触など緊急性がある場合は、画面入力だけに頼らず適切な電話・医療・行政窓口を利用してください。</div></div><div><h3>Evidence Chain</h3><div class="timeline">${ev.map(e=>`<div class="event"><b>${U.esc(e.phase)}</b><div>${U.esc(e.caption)}</div></div>`).join('')||'まだありません'}</div><h3>Next Action</h3>${acts.map(a=>`<div class="item">${U.esc(a.label)}<br>${U.fmt(a.dueAt)}</div>`).join('')||'ありません'}</div></div>`;document.getElementById('add').onclick=()=>{const z=DproDemo.load();DproDemo.addEvidence(z,'u-customer-home',id,{phase:'inquiry',caption:document.getElementById('caption').value||'追加相談（デモ）'});DproDemo.save(z);showDemo(id)}}
  async function loadLive(){try{const j=await U.api('/api/pest/v1/cases');const cases=j.cases||[];document.getElementById('nav').innerHTML=U.nav();app.innerHTML=`<section class="hero"><span class="badge">MY CASES</span><h1>ご依頼・ご相談</h1><p>ご本人に紐づく案件だけを表示しています。</p></section><section class="grid grid-2" style="margin-top:18px">${cases.map(c=>`<div class="card"><h2>${U.esc(c.title)}</h2><p><span class="status ${c.urgency==='high'?'urgent':''}">${U.status(c.status)}</span></p><p>次回: ${U.fmt(c.next_visit)}</p><button class="btn live-open" data-id="${c.id}">案件を開く</button></div>`).join('')||'<div class="card">現在表示できる案件はありません。</div>'}</section><section id="detail" class="card" style="margin-top:18px"><h2>案件を選択してください</h2></section>`;document.querySelectorAll('.live-open').forEach(b=>b.onclick=()=>showLive(b.dataset.id));if(cases[0])showLive(cases[0].id)}catch(e){app.innerHTML=`<section class="card"><h2>読み込めませんでした</h2><p>${U.esc(U.errText(e))}</p></section>`}}
  async function showLive(id){const d=document.getElementById('detail');d.innerHTML='<h2>読み込み中…</h2>';try{const [cr,er,qr,vr,rr,ar]=await Promise.all([U.api(`/api/pest/v1/cases/${id}`),U.api(`/api/pest/v1/cases/${id}/evidence`),U.api(`/api/pest/v1/cases/${id}/quotes`),U.api(`/api/pest/v1/cases/${id}/visits`),U.api(`/api/pest/v1/cases/${id}/reports`),U.api(`/api/pest/v1/cases/${id}/next-actions`)]);const c=cr.case,quotes=qr.quotes||[],visits=vr.visits||[],reports=rr.reports||[],acts=ar.next_actions||[];d.innerHTML=`<h2>${U.esc(c.title)}</h2><p><span class="status">${U.status(c.status)}</span></p><div class="grid grid-2"><div><h3>相談追記</h3><div class="field"><label>状況メモ</label><textarea id="caption" rows="3"></textarea></div><button class="btn" id="add">Evidence Chainへ追加</button><p class="muted">写真ファイル本体はStorage binding後に有効化します。現在は相談メモ・写真参照情報を安全に記録します。</p><h3>再訪依頼</h3><div class="field"><textarea id="revisit" rows="3" placeholder="再発場所・状況など"></textarea></div><button class="btn secondary" id="request-revisit">再訪を依頼</button><p id="msg"></p></div><div><h3>訪問予定</h3>${visits.length?visits.map(v=>`<div class="item">${U.fmt(v.starts_at)} / ${U.esc(v.purpose)}</div>`).join(''):'未確定'}<h3>見積</h3>${quotes.length?quotes.map(q=>`<div class="item"><b>¥${Number(q.total||0).toLocaleString('ja-JP')}</b> <span class="status">${U.status(q.status)}</span><br>${U.esc(q.summary)}${q.status==='sent'?`<div class="row" style="margin-top:8px"><button class="btn quote-response" data-id="${q.id}" data-decision="accepted">承認</button><button class="btn secondary quote-response" data-id="${q.id}" data-decision="declined">辞退</button></div>`:''}</div>`).join(''):'提示済み見積はありません'}<h3>Evidence Chain</h3><div class="timeline">${(er.evidence||[]).map(e=>`<div class="event"><b>${U.esc(e.phase)}</b><div>${U.esc(e.caption||'')}</div><small>${U.fmt(e.created_at)}</small></div>`).join('')||'まだありません'}</div><h3>公開済み報告</h3>${reports.map(r=>`<div class="item">報告 #${U.esc(r.id.slice(0,8))} / ${U.fmt(r.published_at)}</div>`).join('')||'まだありません'}<h3>次のご案内</h3>${acts.filter(a=>a.status==='open').map(a=>`<div class="item">${U.esc(a.label)}<br>${U.fmt(a.due_at)}</div>`).join('')||'ありません'}</div></div>`;
    document.getElementById('add').onclick=async()=>{const msg=document.getElementById('msg');try{await U.api(`/api/pest/v1/cases/${id}/evidence`,{method:'POST',body:JSON.stringify({phase:'inquiry',kind:'note',caption:document.getElementById('caption').value||'追加相談'})});msg.textContent='追記しました';showLive(id)}catch(e){msg.textContent='保存できません: '+U.errText(e)}};
    document.getElementById('request-revisit').onclick=async()=>{const msg=document.getElementById('msg');try{await U.api(`/api/pest/v1/cases/${id}/revisit-request`,{method:'POST',body:JSON.stringify({reason:document.getElementById('revisit').value})});msg.textContent='再訪依頼を受け付けました'}catch(e){msg.textContent='依頼できません: '+U.errText(e)}};
    document.querySelectorAll('.quote-response').forEach(b=>b.onclick=async()=>{try{await U.api(`/api/pest/v1/quotes/${b.dataset.id}/respond`,{method:'POST',body:JSON.stringify({decision:b.dataset.decision})});showLive(id)}catch(e){document.getElementById('msg').textContent='見積回答を保存できません: '+U.errText(e)}});
  }catch(e){d.innerHTML=`<h2>案件を読み込めませんでした</h2><p>${U.esc(U.errText(e))}</p>`}}
})();
