(function(root,factory){const api=factory(); if(typeof module==='object'&&module.exports) module.exports=api; else root.DproDemo=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const KEY='dpro_pest_env_demo_v1';
const transitions={
  new:['triage','cancelled'], triage:['survey_planned','quote_pending','cancelled'], survey_planned:['surveyed','cancelled'], surveyed:['quote_pending','treatment_planned','cancelled'], quote_pending:['treatment_planned','cancelled'], treatment_planned:['in_progress','cancelled'], in_progress:['review_pending','revisit_required'], revisit_required:['treatment_planned','review_pending'], review_pending:['reported','revisit_required'], reported:['closed','revisit_required'], closed:['reopened'], reopened:['triage','survey_planned','treatment_planned'], cancelled:['reopened']
};
const requiredEvidence={in_progress:['before'],review_pending:['before','after']};
function iso(offsetDays=0){const d=new Date(); d.setDate(d.getDate()+offsetDays); return d.toISOString();}
function seed(){return {meta:{systemId:'dpro_pest_env',version:'1.0.0-g4',mode:'DEMO',createdAt:iso()},users:[
{id:'u-owner',name:'山本オーナー',role:'owner',tenantId:'tenant-demo'},
{id:'u-staff-a',name:'田中スタッフ',role:'staff',tenantId:'tenant-demo'},
{id:'u-staff-b',name:'佐藤スタッフ',role:'staff',tenantId:'tenant-demo'},
{id:'u-customer-home',name:'住宅デモ顧客',role:'customer',tenantId:'tenant-demo',customerId:'c-home'},
{id:'u-customer-shop',name:'飲食店デモ担当',role:'customer',tenantId:'tenant-demo',customerId:'c-shop'}],customers:[
{id:'c-home',tenantId:'tenant-demo',type:'household',name:'住宅デモ顧客',phone:'090-0000-0001'},
{id:'c-shop',tenantId:'tenant-demo',type:'business',name:'デモ食堂',phone:'092-000-0002'}],properties:[
{id:'p-home',tenantId:'tenant-demo',customerId:'c-home',name:'デモ住宅',address:'福岡県糟屋郡（デモ）',kind:'house'},
{id:'p-shop',tenantId:'tenant-demo',customerId:'c-shop',name:'デモ食堂 志免店',address:'福岡県糟屋郡志免町（デモ）',kind:'restaurant'}],cases:[
{id:'case-home',tenantId:'tenant-demo',customerId:'c-home',propertyId:'p-home',title:'キッチンでゴキブリ目撃',pest:'cockroach',urgency:'high',status:'survey_planned',assignedStaffId:'u-staff-a',nextVisit:iso(1),serviceType:'single',warrantyDays:30,createdAt:iso(-1)},
{id:'case-shop',tenantId:'tenant-demo',customerId:'c-shop',propertyId:'p-shop',title:'月次ネズミ防除点検',pest:'rodent',urgency:'normal',status:'in_progress',assignedStaffId:'u-staff-b',nextVisit:iso(0),serviceType:'recurring',recurrenceDays:30,createdAt:iso(-29)}],zones:[
{id:'z1',propertyId:'p-shop',name:'厨房'}, {id:'z2',propertyId:'p-shop',name:'バックヤード'}, {id:'z3',propertyId:'p-shop',name:'搬入口'}],traps:[
{id:'t1',propertyId:'p-shop',zoneId:'z1',label:'T-01',type:'sticky',status:'active'},
{id:'t2',propertyId:'p-shop',zoneId:'z2',label:'T-02',type:'box',status:'active'},
{id:'t3',propertyId:'p-shop',zoneId:'z3',label:'T-03',type:'sticky',status:'active'}],evidence:[
{id:'e-inquiry',caseId:'case-home',phase:'inquiry',kind:'photo',caption:'顧客LINE相談写真（デモ）',createdBy:'u-customer-home',createdAt:iso(-1)},
{id:'e-shop-before',caseId:'case-shop',phase:'before',kind:'photo',caption:'厨房点検前（デモ）',zoneId:'z1',createdBy:'u-staff-b',createdAt:iso(0)}],chemicals:[],captures:[],reports:[],checkpoints:[],drafts:{},nextActions:[
{id:'na1',caseId:'case-home',type:'visit',label:'現地調査',dueAt:iso(1),status:'open'},
{id:'na2',caseId:'case-shop',type:'report',label:'月次点検報告を完成',dueAt:iso(0),status:'open'}],audit:[]};}
function deep(v){return JSON.parse(JSON.stringify(v));}
function load(storage){storage=storage||((typeof localStorage!=='undefined')?localStorage:null); if(!storage)return seed(); const raw=storage.getItem(KEY); if(!raw){const s=seed();storage.setItem(KEY,JSON.stringify(s));return s;} try{return JSON.parse(raw)}catch{const s=seed();storage.setItem(KEY,JSON.stringify(s));return s;}}
function save(state,storage){storage=storage||((typeof localStorage!=='undefined')?localStorage:null); if(storage)storage.setItem(KEY,JSON.stringify(state)); return state;}
function reset(storage){const s=seed();return save(s,storage);}
function actor(state,userId){return state.users.find(u=>u.id===userId)||null;}
function canReadCase(state,userId,c){const u=actor(state,userId); if(!u||u.tenantId!==c.tenantId)return false; if(u.role==='owner')return true; if(u.role==='staff')return c.assignedStaffId===u.id; if(u.role==='customer')return c.customerId===u.customerId; return false;}
function visibleCases(state,userId){return state.cases.filter(c=>canReadCase(state,userId,c));}
function audit(state,userId,action,entityId,detail){state.audit.unshift({id:'a-'+Date.now()+'-'+Math.random().toString(16).slice(2),at:new Date().toISOString(),userId,action,entityId,detail:detail||{}});}
function transition(state,userId,caseId,to,reason){const c=state.cases.find(x=>x.id===caseId);const u=actor(state,userId); if(!c||!u||u.tenantId!==c.tenantId)throw new Error('NOT_FOUND_OR_SCOPE'); if(u.role==='customer')throw new Error('ROLE_DENIED'); if(u.role==='staff'&&c.assignedStaffId!==u.id)throw new Error('ASSIGNMENT_DENIED'); if(!transitions[c.status]||!transitions[c.status].includes(to))throw new Error('INVALID_TRANSITION'); if(['cancelled','reopened'].includes(to)&&(!reason||reason.trim().length<3))throw new Error('REASON_REQUIRED'); const phases=requiredEvidence[to]||[]; if(phases.length){const have=new Set(state.evidence.filter(e=>e.caseId===caseId).map(e=>e.phase)); const miss=phases.filter(p=>!have.has(p)); if(miss.length)throw new Error('EVIDENCE_REQUIRED:'+miss.join(','));}
const from=c.status;c.status=to;audit(state,userId,'case.transition',caseId,{from,to,reason:reason||''}); if(to==='reported')generateNextAction(state,c); return c;}
function addEvidence(state,userId,caseId,input){const c=state.cases.find(x=>x.id===caseId); if(!c||!canReadCase(state,userId,c))throw new Error('SCOPE_DENIED'); const u=actor(state,userId); if(u.role==='customer'&&input.phase!=='inquiry')throw new Error('CUSTOMER_PHASE_DENIED'); if(!['inquiry','survey','before','during','after','result'].includes(input.phase))throw new Error('INVALID_PHASE'); const e={id:'e-'+Date.now()+'-'+Math.random().toString(16).slice(2),caseId,phase:input.phase,kind:input.kind||'photo',caption:(input.caption||'').slice(0,180),zoneId:input.zoneId||null,createdBy:userId,createdAt:new Date().toISOString()};state.evidence.push(e);audit(state,userId,'evidence.create',caseId,{phase:e.phase});return e;}
function addChemical(state,userId,caseId,input){const c=state.cases.find(x=>x.id===caseId);const u=actor(state,userId);if(!c||!u||u.role==='customer'||!canReadCase(state,userId,c))throw new Error('ROLE_OR_SCOPE_DENIED');for(const k of ['productName','purpose','amount','unit'])if(!String(input[k]||'').trim())throw new Error('CHEMICAL_REQUIRED:'+k); if(input.confirmedLabel!==true)throw new Error('LABEL_CONFIRMATION_REQUIRED');const r={id:'ch-'+Date.now(),caseId,productName:input.productName,purpose:input.purpose,amount:input.amount,unit:input.unit,dilution:input.dilution||'',confirmedLabel:true,createdBy:userId,createdAt:new Date().toISOString()};state.chemicals.push(r);audit(state,userId,'chemical.create',caseId,{productName:r.productName});return r;}
function addCapture(state,userId,caseId,input){const c=state.cases.find(x=>x.id===caseId);const u=actor(state,userId);if(!c||!u||u.role==='customer'||!canReadCase(state,userId,c))throw new Error('ROLE_OR_SCOPE_DENIED');if(!input.trapId||!String(input.result||'').trim())throw new Error('CAPTURE_REQUIRED');const r={id:'cap-'+Date.now(),caseId,trapId:input.trapId,result:input.result,count:Number(input.count||0),createdBy:userId,createdAt:new Date().toISOString()};state.captures.push(r);audit(state,userId,'capture.create',caseId,{trapId:r.trapId,count:r.count});return r;}
function addSafetyCheckpoint(state,userId,caseId,input){const c=state.cases.find(x=>x.id===caseId);const u=actor(state,userId);if(!c||!u||u.role==='customer'||!canReadCase(state,userId,c))throw new Error('ROLE_OR_SCOPE_DENIED');if(!['site_risk','chemical_label','wildlife_permission','customer_notice'].includes(input.type))throw new Error('INVALID_CHECKPOINT');if(input.confirmed!==true)throw new Error('CHECKPOINT_CONFIRMATION_REQUIRED');const r={id:'sc-'+Date.now(),caseId,type:input.type,confirmed:true,note:(input.note||'').slice(0,240),createdBy:userId,createdAt:new Date().toISOString()};state.checkpoints.push(r);audit(state,userId,'safety.confirm',caseId,{type:r.type});return r;}
function buildReport(state,userId,caseId){const c=state.cases.find(x=>x.id===caseId);const u=actor(state,userId);if(!c||!u||u.role==='customer'||!canReadCase(state,userId,c))throw new Error('ROLE_OR_SCOPE_DENIED');const phases=new Set(state.evidence.filter(e=>e.caseId===caseId).map(e=>e.phase));for(const p of ['before','after'])if(!phases.has(p))throw new Error('REPORT_EVIDENCE_REQUIRED:'+p);const existing=state.reports.find(r=>r.caseId===caseId&&r.status!=='revoked');if(existing)return existing;const r={id:'r-'+Date.now(),caseId,status:'review',createdBy:userId,createdAt:new Date().toISOString(),summary:{evidenceCount:state.evidence.filter(e=>e.caseId===caseId).length,chemicalCount:state.chemicals.filter(e=>e.caseId===caseId).length,captureCount:state.captures.filter(e=>e.caseId===caseId).length}};state.reports.push(r);audit(state,userId,'report.build',caseId,r.summary);return r;}
function approveReport(state,userId,reportId){const u=actor(state,userId),r=state.reports.find(x=>x.id===reportId);if(!u||u.role!=='owner'||!r)throw new Error('OWNER_APPROVAL_REQUIRED');const c=state.cases.find(x=>x.id===r.caseId);if(!c||c.tenantId!==u.tenantId)throw new Error('SCOPE_DENIED');r.status='published';r.approvedBy=userId;r.publishedAt=new Date().toISOString();if(c.status==='review_pending')c.status='reported';generateNextAction(state,c);audit(state,userId,'report.approve',c.id,{reportId});return r;}
function saveDraft(state,userId,caseId,draft){const c=state.cases.find(x=>x.id===caseId);if(!c||!canReadCase(state,userId,c))throw new Error('SCOPE_DENIED');state.drafts[userId+':'+caseId]={...draft,updatedAt:new Date().toISOString()};return state.drafts[userId+':'+caseId];}
function loadDraft(state,userId,caseId){return state.drafts[userId+':'+caseId]||null;}
function generateNextAction(state,c){state.nextActions=state.nextActions.filter(x=>!(x.caseId===c.id&&x.status==='open'&&['warranty','recurring'].includes(x.type)));let due,type,label;if(c.serviceType==='recurring'){due=new Date();due.setDate(due.getDate()+(c.recurrenceDays||30));type='recurring';label='次回定期点検';}else if(c.warrantyDays){due=new Date();due.setDate(due.getDate()+c.warrantyDays);type='warranty';label='保証期限確認';}if(due)state.nextActions.push({id:'na-'+Date.now(),caseId:c.id,type,label,dueAt:due.toISOString(),status:'open'});}
function summary(state,userId){const cs=visibleCases(state,userId);return {cases:cs.length,urgent:cs.filter(c=>c.urgency==='high'&&!['closed','cancelled'].includes(c.status)).length,todayActions:state.nextActions.filter(a=>cs.some(c=>c.id===a.caseId)&&a.status==='open').length,reports:state.reports.filter(r=>cs.some(c=>c.id===r.caseId)).length};}
return {KEY,transitions,seed,load,save,reset,actor,canReadCase,visibleCases,transition,addEvidence,addChemical,addCapture,addSafetyCheckpoint,buildReport,approveReport,saveDraft,loadDraft,generateNextAction,summary,deep};
});
