(async function(){
  const U=DPRO_UI,app=document.getElementById('app');document.getElementById('nav').innerHTML=U.nav();U.setModeBanner('割当案件だけを表示・現場記録');
  if(U.demo){renderDemo();return}await U.protect(['staff','owner','dpro_admin'],async()=>loadLive());
  function renderDemo(){const uid=new URLSearchParams(location.search).get('staff')==='a'?'u-staff-a':'u-staff-b',s=DproDemo.load(),cases=DproDemo.visibleCases(s,uid);app.innerHTML=`<section class="hero"><span class="badge">${U.esc(DproDemo.actor(s,uid).name)}</span><h1>本日の担当</h1><p>他スタッフの未割当案件は表示しません。</p></section><section class="grid grid-2" style="margin-top:18px">${cases.map(c=>`<div class="card"><h2>${U.esc(c.title)}</h2><p><span class="status">${U.status(c.status)}</span> ${U.fmt(c.nextVisit)}</p><button class="btn open" data-id="${c.id}">現場カルテを開く</button></div>`).join('')||'<div class="card">担当案件はありません</div>'}</section><section class="card" id="detail" style="margin-top:18px"><h2>案件を選択してください</h2></section>`;document.querySelectorAll('.open').forEach(b=>b.onclick=()=>showDemo(uid,b.dataset.id));if(cases[0])showDemo(uid,cases[0].id)}
  function showDemo(uid,id){const st=DproDemo.load(),c=st.cases.find(x=>x.id===id),ev=st.evidence.filter(e=>e.caseId===id);document.getElementById('detail').innerHTML=`<h2>${U.esc(c.title)}</h2>${fieldForm(ev)}<p id="msg"></p>`;const dr=DproDemo.loadDraft(st,uid,id);if(dr){document.getElementById('cap').value=dr.caption||'';document.getElementById('phase').value=dr.phase||'survey'}document.getElementById('draft').onclick=()=>{const a=DproDemo.load();DproDemo.saveDraft(a,uid,id,{phase:document.getElementById('phase').value,caption:document.getElementById('cap').value});DproDemo.save(a);document.getElementById('msg').textContent='端末内に下書きを保存しました'};document.getElementById('evadd').onclick=()=>{try{const a=DproDemo.load();DproDemo.addEvidence(a,uid,id,{phase:document.getElementById('phase').value,caption:document.getElementById('cap').value||'現場記録（デモ）'});DproDemo.save(a);showDemo(uid,id)}catch(e){document.getElementById('msg').textContent='BLOCK: '+e.message}};document.getElementById('safety').onclick=()=>{try{const a=DproDemo.load();DproDemo.addSafetyCheckpoint(a,uid,id,{type:'site_risk',confirmed:document.getElementById('riskok').checked,note:'現場確認（デモ）'});DproDemo.save(a);document.getElementById('msg').textContent='安全確認を記録しました'}catch(e){document.getElementById('msg').textContent='BLOCK: '+e.message}};document.getElementById('chem').onclick=()=>{try{const a=DproDemo.load();DproDemo.addChemical(a,uid,id,{productName:document.getElementById('prod').value,purpose:document.getElementById('purpose').value,amount:document.getElementById('amount').value,unit:document.getElementById('unit').value,confirmedLabel:document.getElementById('labelok').checked});DproDemo.save(a);document.getElementById('msg').textContent='薬剤記録を保存しました'}catch(e){document.getElementById('msg').textContent='BLOCK: '+e.message}};document.getElementById('report').onclick=()=>{try{const a=DproDemo.load();const r=DproDemo.buildReport(a,uid,id);DproDemo.save(a);document.getElementById('msg').textContent='報告をOwner確認待ちにしました: '+r.id}catch(e){document.getElementById('msg').textContent='BLOCK: '+e.message}}}
  function fieldForm(ev){return `<div class="grid grid-2"><div><h3>Evidence Chain</h3><div class="field"><select id="phase"><option>survey</option><option>before</option><option>during</option><option>after</option><option>result</option></select></div><div class="field"><input id="cap" placeholder="写真/所見メモ"></div><div class="row"><button class="btn secondary" id="draft">オフライン下書き保存</button><button class="btn" id="evadd">記録を追加</button></div><h3>現調記録</h3><div class="field"><textarea id="findings" rows="3" placeholder="発生状況・侵入経路・被害状況"></textarea></div><button class="btn secondary" id="inspection">現調を保存</button><h3>施工記録</h3><div class="field"><input id="method" placeholder="方法 例：侵入口封鎖"></div><div class="field"><textarea id="treatment-detail" rows="3" placeholder="施工内容"></textarea></div><button class="btn secondary" id="treatment">施工を保存</button></div><div><h3>薬剤記録</h3><div class="field"><input id="prod" placeholder="製品名"></div><div class="field"><input id="purpose" placeholder="使用目的"></div><div class="row"><input id="amount" placeholder="量" style="padding:10px;border:1px solid #ccc;border-radius:9px;width:110px"><input id="unit" placeholder="単位" style="padding:10px;border:1px solid #ccc;border-radius:9px;width:110px"></div><label><input type="checkbox" id="labelok"> ラベル/事業者基準を確認した</label><br><br><button class="btn secondary" id="chem">薬剤記録を追加</button><h3>安全確認</h3><label><input type="checkbox" id="riskok"> 現場リスク/周囲への配慮事項を確認した</label><br><br><button class="btn secondary" id="safety">安全確認を記録</button><h3>報告書</h3><button class="btn secondary" id="report">Before/Afterから報告を作成</button><h3>現在のEvidence</h3><div class="timeline">${(ev||[]).map(e=>`<div class="event"><b>${U.esc(e.phase)}</b><div>${U.esc(e.caption||'')}</div></div>`).join('')||'まだありません'}</div></div></div>`}
  async function loadLive(){try{const j=await U.api('/api/pest/v1/cases'),cases=j.cases||[];document.getElementById('nav').innerHTML=U.nav();app.innerHTML=`<section class="hero"><span class="badge">FIELD</span><h1>本日の担当</h1><p>Worker側でも担当案件scopeを再検証します。</p></section><section class="grid grid-2" style="margin-top:18px">${cases.map(c=>`<div class="card"><h2>${U.esc(c.title)}</h2><p><span class="status">${U.status(c.status)}</span></p><p>${U.fmt(c.next_visit)}</p><button class="btn live-open" data-id="${c.id}">現場カルテを開く</button></div>`).join('')||'<div class="card">担当案件はありません。</div>'}</section><section class="card" id="detail" style="margin-top:18px"><h2>案件を選択してください</h2></section>`;document.querySelectorAll('.live-open').forEach(b=>b.onclick=()=>showLive(b.dataset.id));if(cases[0])showLive(cases[0].id)}catch(e){app.innerHTML=`<section class="card"><h2>読み込めませんでした</h2><p>${U.esc(U.errText(e))}</p></section>`}}
  async function showLive(id){const d=document.getElementById('detail');d.innerHTML='<h2>読み込み中…</h2>';try{const [cr,er]=await Promise.all([U.api(`/api/pest/v1/cases/${id}`),U.api(`/api/pest/v1/cases/${id}/evidence`)]);d.innerHTML=`<h2>${U.esc(cr.case.title)}</h2>${fieldForm(er.evidence||[])}<p class="muted">写真ファイル本体のアップロードはEvidence Storage binding後に有効化します。メタデータ・所見・施工・薬剤・安全確認は本番DBへ保存できます。</p><p id="msg"></p>`;const key='dpro_pest_draft_'+id;try{const draft=JSON.parse(localStorage.getItem(key)||'null');if(draft){document.getElementById('cap').value=draft.caption||'';document.getElementById('phase').value=draft.phase||'survey'}}catch{}
    const msg=()=>document.getElementById('msg');document.getElementById('draft').onclick=()=>{localStorage.setItem(key,JSON.stringify({phase:document.getElementById('phase').value,caption:document.getElementById('cap').value,savedAt:new Date().toISOString()}));msg().textContent='この端末に下書きを保存しました'};
    document.getElementById('evadd').onclick=async()=>{try{await U.api(`/api/pest/v1/cases/${id}/evidence`,{method:'POST',body:JSON.stringify({phase:document.getElementById('phase').value,kind:'note',caption:document.getElementById('cap').value||'現場記録'})});localStorage.removeItem(key);showLive(id)}catch(e){msg().textContent='保存できません: '+U.errText(e)}};
    document.getElementById('inspection').onclick=async()=>{try{await U.api(`/api/pest/v1/cases/${id}/inspections`,{method:'POST',body:JSON.stringify({findings:document.getElementById('findings').value})});msg().textContent='現調記録を保存しました'}catch(e){msg().textContent='保存できません: '+U.errText(e)}};
    document.getElementById('treatment').onclick=async()=>{try{await U.api(`/api/pest/v1/cases/${id}/treatments`,{method:'POST',body:JSON.stringify({method:document.getElementById('method').value,detail:document.getElementById('treatment-detail').value})});msg().textContent='施工記録を保存しました'}catch(e){msg().textContent='保存できません: '+U.errText(e)}};
    document.getElementById('chem').onclick=async()=>{try{await U.api(`/api/pest/v1/cases/${id}/chemicals`,{method:'POST',body:JSON.stringify({product_name:document.getElementById('prod').value,purpose:document.getElementById('purpose').value,amount:document.getElementById('amount').value,unit:document.getElementById('unit').value,confirmed_label:document.getElementById('labelok').checked})});msg().textContent='薬剤記録を保存しました'}catch(e){msg().textContent='BLOCK: '+U.errText(e)}};
    document.getElementById('safety').onclick=async()=>{try{await U.api(`/api/pest/v1/cases/${id}/safety-checkpoints`,{method:'POST',body:JSON.stringify({type:'site_risk',confirmed:document.getElementById('riskok').checked,note:'現場リスク確認'})});msg().textContent='安全確認を記録しました'}catch(e){msg().textContent='BLOCK: '+U.errText(e)}};
    document.getElementById('report').onclick=async()=>{try{await U.api(`/api/pest/v1/cases/${id}/reports`,{method:'POST',body:'{}'});msg().textContent='報告をOwner確認待ちにしました'}catch(e){msg().textContent='BLOCK: '+U.errText(e)}};
  }catch(e){d.innerHTML=`<h2>案件を読み込めませんでした</h2><p>${U.esc(U.errText(e))}</p>`}}
})();
