(function(root){
  const q=new URLSearchParams(location.search),demo=q.get('demo')==='1';
  const cfg=()=>root.DPRO_CONFIG||{};
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const fmt=d=>d?new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short'}).format(new Date(d)):'-';
  const status=s=>({new:'新規',triage:'確認中',survey_planned:'現調予定',surveyed:'現調済',quote_pending:'見積中',treatment_planned:'施工予定',in_progress:'作業中',review_pending:'報告確認待ち',revisit_required:'再訪必要',reported:'報告済',closed:'完了',reopened:'再開',cancelled:'取消',draft:'下書き',sent:'提示済',accepted:'承認',declined:'辞退',published:'公開済'}[s]||s);
  const tokenKey='dpro_pest_env_access_token';
  const profileKey='dpro_pest_env_profile';
  function token(){return sessionStorage.getItem(tokenKey)||''}
  function profile(){try{return JSON.parse(sessionStorage.getItem(profileKey)||'null')}catch{return null}}
  function saveSession(j){sessionStorage.setItem(tokenKey,j.access_token);sessionStorage.setItem(profileKey,JSON.stringify(j.profile||{}))}
  function logout(){sessionStorage.removeItem(tokenKey);sessionStorage.removeItem(profileKey);location.reload()}
  function base(){return String(cfg().apiBase||'').replace(/\/$/,'')}
  async function api(path,opts={}){if(!base())throw new Error('PRODUCTION_API_NOT_CONFIGURED');const isForm=typeof FormData!=='undefined'&&opts.body instanceof FormData;const headers={...(isForm?{}:{'content-type':'application/json'}),...(opts.headers||{})};if(token())headers.authorization='Bearer '+token();const r=await fetch(base()+path,{...opts,headers});let j={};try{j=await r.json()}catch{}if(r.status===401&&path!=='/api/pest/v1/auth/login'){sessionStorage.removeItem(tokenKey);sessionStorage.removeItem(profileKey)}if(!r.ok){const e=new Error(j.error?.message||`HTTP ${r.status}`);e.code=j.error?.code;e.status=r.status;e.details=j.error?.details;throw e}return j}
  function nav(){const d=demo?'?demo=1':'';return `<div class="nav"><a href="index.html${d}">入口</a><a href="customer.html${d}">Customer</a><a href="owner.html${d}">Owner</a><a href="staff.html${d}">Staff</a><a href="owner-ipad.html${d}">iPad</a><a href="tutorial.html${d}">Tutorial</a><a href="guide-center.html${d}">Guide</a><a href="demo-prepare.html?demo=1">Demo Prepare</a><a href="system-check.html${d}">System Check</a><a href="ready-control-center.html${d}">READY</a>${!demo&&token()?'<button class="btn secondary" type="button" onclick="DPRO_UI.logout()">ログアウト</button>':''}</div>`}
  function setModeBanner(roleText=''){const el=document.getElementById('mode-banner');if(!el)return;el.className='demo-banner '+(demo?'':'prod-banner');el.textContent=demo?`DEMO — ${roleText}`:`PRODUCTION — ${roleText}`}
  function configured(){return !!(cfg().productionConfigured&&base())}
  function renderNotConfigured(){const a=document.getElementById('app')||document.body;a.innerHTML='<section class="hero"><span class="badge">SAFE HOLD</span><h1>本番接続はまだ有効化されていません</h1><p>デモはURL末尾に <code>?demo=1</code> を付けて確認できます。本番Worker URL確定後にこの画面を有効化します。</p></section>'}
  function renderLogin(roles,onReady){const a=document.getElementById('app');a.innerHTML=`<section class="hero"><span class="badge">PRODUCTION LOGIN</span><h1>ログイン</h1><p>Supabase AuthはブラウザからDBへ直接接続せず、DPRO Worker経由で認証します。</p></section><form class="card" id="login-form" style="margin-top:18px"><div class="field"><label>メールアドレス</label><input type="email" id="login-email" autocomplete="username" required></div><div class="field"><label>パスワード</label><input type="password" id="login-password" autocomplete="current-password" required></div><button class="btn" type="submit">ログイン</button><p id="login-msg"></p></form>`;document.getElementById('login-form').onsubmit=async e=>{e.preventDefault();const msg=document.getElementById('login-msg');msg.textContent='確認中…';try{const j=await api('/api/pest/v1/auth/login',{method:'POST',body:JSON.stringify({email:document.getElementById('login-email').value,password:document.getElementById('login-password').value})});if(roles.length&&!roles.includes(j.profile.role)){msg.textContent='この画面を利用できる権限ではありません。';return}saveSession(j);location.reload()}catch(err){msg.textContent='ログインできません: '+err.message}}}
  async function protect(roles,onReady){if(demo)return false;if(!configured()){renderNotConfigured();return false}let p=profile();if(!token()||!p){renderLogin(roles,onReady);return false}try{const j=await api('/api/pest/v1/auth/me');p=j.profile;sessionStorage.setItem(profileKey,JSON.stringify(p));if(roles.length&&!roles.includes(p.role)){(document.getElementById('app')||document.body).innerHTML='<section class="hero"><h1>権限がありません</h1><p>このアカウントではこの画面を利用できません。</p><button class="btn" onclick="DPRO_UI.logout()">ログアウト</button></section>';return false}await onReady(p);return true}catch(e){sessionStorage.removeItem(tokenKey);sessionStorage.removeItem(profileKey);renderLogin(roles,onReady);return false}}
  function errText(e){return `${e.code?e.code+': ':''}${e.message||'エラー'}`}
  root.DPRO_UI={demo,qs:q,esc,fmt,status,nav,api,protect,logout,token,profile,configured,setModeBanner,errText,saveSession};
})(window);
